name: Build TextUtilities

on:
  push:
    branches: ["main"]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.config.os }}-latest
    strategy:
      matrix:
        config:
          - os: windows
            os_name: windows
            cmd: compress.bat
          - os: ubuntu
            os_name: linux
            cmd: compress.sh
          - os: macos
            os_name: macos
            cmd: compress.sh

    steps:
      - uses: actions/checkout@v3

      - name: Permission
        if: matrix.config.os == 'ubuntu' || matrix.config.os == 'macos'
        run: chmod +x compress.sh

      - name: Build TextUtilities App
        run: |
          ./${{ matrix.config.cmd }} textutilities

      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.config.os }}
          path: ${{github.workspace}}/**

      - name: Upload Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "textutilities_${{ matrix.config.os_name }}"
          files: |
            textutilities_${{ matrix.config.os_name }}.shflapp